Handle /dev/null correctly

diff --git a/src/out b/src/out
--- a/src/out
+++ b/src/out
@@ -27,9 +27,11 @@ message=$(                echo "${input_json}" | jq -r --arg default "The job $B
 labels=$(                 echo "${input_json}" | jq -c '.params.labels? // {}'                                                                 )
 additional_details_file=$(echo "${input_json}" | jq -r '.params.additional_details_file? // "/dev/null"'                                       )
 
-if [[ ! -f "$additional_details_file" ]] || [[ ! -r "$additional_details_file" ]]; then
-  echo >&2 "[ERROR][additonal_details_file: ${additional_details_file}] The additional_details_file was not found, or not readable!"
-  exit 1
+if [[ "$additional_details_file" != /dev/null ]]; then
+  if [[ ! -f "$additional_details_file" ]] || [[ ! -r "$additional_details_file" ]]; then
+    echo >&2 "[ERROR][additonal_details_file: ${additional_details_file}] The additional_details_file was not found, or not readable!"
+    exit 1
+  fi
 fi
 
 body=$(jq -c \
